object Dependencies {
    const val kotlin_std = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin_std}"
    const val coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines_android}"
    const val coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines_core}"
    const val kotlin_test = "org.jetbrains.kotlin:kotlin-test:${Versions.kotlin_test}"
    const val kotlin_test_junit = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlin_test}"
    const val mockito_kotlin = "org.mockito.kotlin:mockito-kotlin:${Versions.mockito_kotlin}"
    const val kotlin_coroutine_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.kotlin_coroutine_test}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"
    const val mockwebserver = "com.squareup.okhttp3:mockwebserver:${Versions.mockwebserver}"
    const val json = "org.json:json:${Versions.json}"
    const val junit = "junit:junit:${Versions.jUnit}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hilt_compiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val compose_runtime = "androidx.compose.runtime:runtime:${Versions.compose}"
    const val compose_ui = "androidx.compose.ui:ui:${Versions.compose}"
    const val compose_ui_tooling = "androidx.compose.ui:ui-tooling:${Versions.compose}"
    const val compose_ui_tooling_preview = "androidx.compose.ui:ui-tooling-preview:${Versions.compose}"
    const val compose_material = "androidx.compose.material:material:${Versions.compose}"
    const val compose_foundation = "androidx.compose.foundation:foundation:${Versions.compose}"
    const val compose_foundation_layout = "androidx.compose.foundation:foundation-layout:${Versions.compose}"
    const val activity_compose = "androidx.activity:activity-compose:${Versions.activity_compose}"
    const val lifecycle_runtime_ktx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"

}